---
# handlers file for ansible-role-openvpn-client
- name: Enable OpenVPN client
  systemd:
    name: "openvpn@{{ item.name }}.service"
    state: restarted
    daemon_reload: yes
    enabled: yes
  with_items: "{{ openvpn_client }}"
